### ISSUE TITLE
CredentialsSupportedRequired Exception

### ISSUE THREAD

**Issue by ehanoc** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#87]
- Launched the sample ui app; 
- Went into documents 
- Following exception happend:

```
 eu.europa.ec.eudi.openid4vci.CredentialIssuerMetadataValidationError$CredentialsSupportedRequired: java.lang.IllegalArgumentException: Credentials Supported Required
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.toDomain(CredentialIssuerMetadataJsonParser.kt:293)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.access$toDomain(CredentialIssuerMetadataJsonParser.kt:1)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParser.parseMetaData(CredentialIssuerMetadataJsonParser.kt:42)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver.resolve-oWdWWdE(DefaultCredentialIssuerMetadataResolver.kt:40)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver$resolve$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Credentials Supported Required
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.toDomain(CredentialIssuerMetadataJsonParser.kt:293) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.access$toDomain(CredentialIssuerMetadataJsonParser.kt:1) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParser.parseMetaData(CredentialIssuerMetadataJsonParser.kt:42) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver.resolve-oWdWWdE(DefaultCredentialIssuerMetadataResolver.kt:40) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver$resolve$1.invokeSuspend(Unknown Source:15) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693) 
```

## Device
- Sony Xperia V I 
- Android 14

**Comment by stzouvaras** [comment]
Hi @ehanoc,

the demo flavor which uses the production issuer is not yet ready for draft 13. Please use the dev flavor to issue new documents.

**Comment by ehanoc** [comment]
@stzouvaras I was in development mode. I just launched from Android Studio and picked "Add Document" => "National ID" and crashed.
