### ISSUE TITLE
Error on Android EUDI app clicking new National ID

### ISSUE THREAD

**Issue by Vytek** [eu-digital-identity-wallet/eudi-app-android-wallet-ui#91]
Summary of the steps taken:
1) Clone repo at version: 0ca76b0c03b52fc811b06b6896dd5bc43c9f7c31
2) Build using Android Studio Version: Jellifish.2023.3.1
3) Create and confirm personal PIN
4) Click on "National ID":

The app return:
![photo_2024-05-08_12-24-22](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/2614303/8d7cf069-6735-43ff-b354-2fb9bbdfa6a9)

Using logcat:

```
OpenId4VciManager       eu.europa.ec.euidi                   E  issueDocument
                                                                                                    eu.europa.ec.eudi.openid4vci.CredentialIssuerMetadataValidationError$CredentialsSupportedRequired: java.lang.IllegalArgumentException: Credentials Supported Required
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.toDomain(CredentialIssuerMetadataJsonParser.kt:293)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.access$toDomain(CredentialIssuerMetadataJsonParser.kt:1)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParser.parseMetaData(CredentialIssuerMetadataJsonParser.kt:42)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver.resolve-oWdWWdE(DefaultCredentialIssuerMetadataResolver.kt:40)
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver$resolve$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Credentials Supported Required
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.toDomain(CredentialIssuerMetadataJsonParser.kt:293) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParserKt.access$toDomain(CredentialIssuerMetadataJsonParser.kt:1) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.formats.CredentialIssuerMetadataJsonParser.parseMetaData(CredentialIssuerMetadataJsonParser.kt:42) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver.resolve-oWdWWdE(DefaultCredentialIssuerMetadataResolver.kt:40) 
                                                                                                    	at eu.europa.ec.eudi.openid4vci.internal.DefaultCredentialIssuerMetadataResolver$resolve$1.invokeSuspend(Unknown Source:15) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693) 

```

**Reasons**

As in the downloadable release version, the app should launch the browser and activate:

PID form for your EUDI Wallet
https://preprod.issuer.eudiw.dev/V04/form

passing the relevant data to create a new test PID credential. Is this an option when compiling the app? Or just an issue? How fix the issue?
[logcat.txt](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/files/15247672/logcat.txt)

Thank you very much and please update us.

**Comment by Wonko-42** [comment]
Good evening @stzouvaras, how should the flavor be changed? I tried adding appFlavor="devDebug" at the end of the gradle.properties file but it keeps building demo?

**Comment by stzouvaras** [comment]
Hi @Wonko-42 

Open the Build Variants menu and select devDebug for the module app (the first one), and it will automatically change all modules for you.

![Screenshot 2024-06-03 155944](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/assets/129499766/110071c8-34ca-4c60-9921-6fd23f9acfb7)
